# Generated by Django 3.1.6 on 2021-02-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.IntegerField(max_length=10)),
                ('Subscription_id', models.CharField(max_length=300)),
                ('TotalAmount', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubscriptionType', models.CharField(max_length=300, unique=True)),
                ('NumberofDuration', models.IntegerField(max_length=5)),
                ('TotalAmount', models.IntegerField(max_length=5)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
                ('image', models.FileField(upload_to='pics/')),
                ('category', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
