# Generated by Django 3.1.6 on 2021-02-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='pics')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
